#!/bin/bash

params=( `cat "zmert_winHelp/SDecoder_cfg.txt" `)
exec=winHelp_gen_zmert.sh
kBest=$( printf "%.0f" ${params[1]} )
interpolationFactor=${params[3]}
f=1
path=/home/konstas/EDI/Generator
inputLists=$path/data/branavan/winHelpHLA/folds/docs.newAnnotation.removedOutliers
output=$path/zmert_winHelp/model_3_no_null_pos_auto_fold${f}_zmert_goldLength
modelPath=$path/results/output/winHelp/alignments/pos/model_3_docs_no_null_newAnnotation
dmvPath=$path/results/output/winHelp/dmv/train/winHelp_uniformZ_initNoise_POS_auto_100
ngramModelPath=$path/winHelpLM/docs.newAnnotation

#echo $kBest
#echo $interpolationFactor
rm -fr ${output}
mkdir -p ${output}

./${exec} ${inputLists}/winHelpFold${f}Eval.tagged \
	${output} \
	${modelPath}/fold${f} \
	${dmvPath}/fold${f} \
	${ngramModelPath}/kylm-abs-winHelpRL-docs-fold${f}-3-gram.model.arpa \
	${kBest} \
	${interpolationFactor} \
	${numThreads}

