package induction.utils;

import induction.Utils;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author sinantie
 */
public class ReorderAlignmentPredictions
{   
    // predFile contains the actual predictions generated by the alignment model,
    // one example per line. RefFile contains the alignments associated with their key.
    String predFile, refFile, prefix;
    List<String[]> examples;    
    
    public ReorderAlignmentPredictions(String goldPath, String predFile, String refFile, boolean examplesInSingleFile, String prefix)
    {
        this.predFile = predFile;
        this.refFile = refFile;
        this.prefix = prefix;
        examples = Utils.readEvent3Examples(goldPath, examplesInSingleFile);
    }
    
    public void execute()
    {
        String[] predictions = Utils.readLines(predFile);
        String[] predictionsOrdered = new String[predictions.length];
        Map<String, Integer> refMap = new HashMap<String, Integer>();
        int i = 0;
        // grab id and order in file
        for(String ex : Utils.readLines(refFile))
        {
            String key = ex.split(":")[0];
            if(!prefix.isEmpty())            
                key = Utils.stripExtension(key.substring(key.indexOf(prefix)));
            refMap.put(key, i++);
            System.out.println(i);
        }
        i = 0;
        // match ids
        for(String[] ex : examples)
        {
            Integer id = refMap.get(ex[0]);
            if(id != null)
            {
                predictionsOrdered[i++] = predictions[id];
            }
            else
            {
                System.out.println("Could not find example " + ex[0]);
            }
        }
        // write output
        Utils.writeLines(predFile + ".sorted", predictionsOrdered);                        
    }
    
    public static void main(String[] args)
    {
        String prefix = "data/weather-data-full/data/";
        String goldFile = "data/weatherGov/weatherGovTrainGaborRecordTreebankUnaryRules.gz";
        String predFile = "results/output/weatherGov/alignments/model_3_gabor_no_sleet_windChill_15iter/stage1.train.pred.14";
        String refFile = "results/output/weatherGov/alignments/model_3_gabor_no_sleet_windChill_15iter/stage1.train.full-pred.14";        
        boolean examplesInSingleFile = true;
        ReorderAlignmentPredictions rep = new ReorderAlignmentPredictions(goldFile, predFile, refFile, examplesInSingleFile, prefix);
        rep.execute();
    }
}
